sudo: required
language: cpp
compiler:
  - gcc
  #- clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
- sudo apt-get install -y openssl libssl-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script: ./build.sh